# Generated by Django 2.2.7 on 2019-11-23 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('physical', '0001_initial'),
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrecord',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='physical.Document'),
        ),
        migrations.AddField(
            model_name='documentrecord',
            name='document_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='metadata.DocumentFormat'),
        ),
    ]
