# Generated by Django 2.2.7 on 2019-11-24 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_auto_20191123_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrecord',
            name='coverage_text',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='documentrecord',
            name='document_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='metadata.DocumentSubject'),
        ),
        migrations.AlterField(
            model_name='documentrecord',
            name='document_format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='metadata.DocumentFormat'),
        ),
    ]
