# Generated by Django 2.2.7 on 2019-11-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_auto_20191124_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentformat',
            name='label',
            field=models.CharField(max_length=800, unique=True),
        ),
        migrations.AlterField(
            model_name='documentsubject',
            name='label',
            field=models.CharField(max_length=800, unique=True),
        ),
    ]
