# Generated by Django 2.2.7 on 2019-11-29 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0004_auto_20191125_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentformat',
            options={'ordering': ['label']},
        ),
        migrations.AlterModelOptions(
            name='documentsubject',
            options={'ordering': ['label']},
        ),
    ]
