# Generated by Django 2.2.7 on 2019-11-24 21:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical', '0001_initial'),
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['topic_model', 'index']},
        ),
        migrations.RemoveField(
            model_name='topicmodel',
            name='document_collection',
        ),
        migrations.AddField(
            model_name='topic',
            name='index',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='document_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='documents',
            field=models.ManyToManyField(related_name='topic_models', to='physical.Document'),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='created_model',
            field=models.FilePathField(null=True, path='/vol/models'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('topic_model', 'index')},
        ),
        migrations.DeleteModel(
            name='DocumentCollection',
        ),
    ]
