# Generated by Django 2.2.7 on 2019-11-25 02:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0002_auto_20191124_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicmodel',
            name='document_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), size=None),
        ),
    ]
