# Generated by Django 2.2.7 on 2019-11-25 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0003_auto_20191124_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttopic',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_relationship', to='physical.Document'),
        ),
        migrations.AlterField(
            model_name='documenttopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_relationship', to='text.Topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='documents',
            field=models.ManyToManyField(related_name='topics', through='text.DocumentTopic', to='physical.Document'),
        ),
    ]
