# Generated by Django 2.2.7 on 2019-11-28 01:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0005_auto_20191127_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmodel',
            name='chunksize',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='iterations',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='min_count',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='no_above',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='no_below',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='passes',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='created_model',
            field=models.FilePathField(editable=False, null=True, path='/vol/models'),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='document_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), editable=False, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='documents',
            field=models.ManyToManyField(editable=False, related_name='topic_models', to='physical.Document'),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='n_topics',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
