# Generated by Django 2.2.7 on 2019-11-29 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0006_auto_20191127_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicmodel',
            name='no_below',
        ),
    ]
